# Use the official Node.js image as the base image
FROM node:22

# Set working directory for all build stages.
WORKDIR /src/app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY . .

# Build the React application
RUN npm run build

# Install a simple HTTP server to serve the static files
RUN npm install -g serve

# Expose the port that the application listens on.
EXPOSE 5173

# Run the application.
CMD  npm run dev
