const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || "";

import axios from "axios";
// uploade file or image or text to the server and create a lesson in the database , 
// return the lesson objectID
export const uploadLesson = async (data, title, type, username) => {
  const token = localStorage.getItem("access_token") || null;
  const formData = new FormData();
  // Add common fields
  formData.append('title', title); 
  formData.append('username', username); 
  // Add content based on type
  if (type === 'file') {
    formData.append('file', data, data.name);
  } 
  else if (type === 'text') {
    formData.append('text', data);
  }

  // Log form data for debugging
  for (let [key, value] of formData.entries()) {
    console.log('FormData:', key, value);
  }

  try {
    const response = await axios.post(
    API_BASE_URL + '/api/upload', 
      formData, 
      {
        headers: {
          'Content-Type': 'multipart/form-data',
          "Authorization": `Bearer ${token}`
        },
      }
    );
    // Log the response for debugging
    console.log('Upload response:', response.data);
    return response.data;
  } catch (error) {
    console.error("Error uploading file:", error);
    if (error.response) {
      // Server responded with error status
      throw new Error(error.response.data.message || 'Upload failed');
    } else if (error.request) {
      // No response received
      throw new Error('Network error - no response from server');
    } else {
      // Other errors
      throw new Error('Upload failed: ' + error.message);
    }
  }
}
// generate Quiz 
export const generateQuiz = async (quizsetup) => {
  const token = localStorage.getItem("access_token") || null;
  try {
    const response = await axios.post(
      API_BASE_URL + "/api/create_quiz",
      quizsetup,
      {
        headers: {
          'Content-Type': 'application/json',
          "Authorization": `Bearer ${token}`
        },
      }
    );
    // Log the response for debugging
    console.log('Quiz generation response:', response.data);
    return response.data;
  } catch (error) {
    console.error("Error generating quiz:", error);
    throw error;
  }
}
// save the quiz result to the database 
export const saveQuizResult = async (result) => {
  const token = localStorage.getItem("access_token") || null;
  try {
    const response = await axios.post(API_BASE_URL + "/api/quiz_results/insert", {result}, {
        headers: {
          'Content-Type': 'application/json',
          "Authorization": `Bearer ${token}`
        },
      });
    // Log the response for debugging
    console.log('Quiz result saved:', response.data);
    return response.data;
  }
  catch (error) {
    console.error("Error saving quiz result:", error);
    throw error;
  }
}
// generate flashcards 
export const generateFlashcards = async (lesson_id,quiz_ress_id,isProfessor) => {
  const token = localStorage.getItem("access_token") || null;
  try {
    const response = await axios.get(API_BASE_URL + `/api/flashcards/${lesson_id}/${quiz_ress_id}`, {
      params: isProfessor ? { isFromProf: true } : {},
      headers: {
        'Content-Type': 'application/json',
        "Authorization": `Bearer ${token}`
      },
    });
    // Log the response for debugging
    console.log('Flashcards generateed:', response.data);
    return response.data;
  }
  catch (error) {
    console.error("Error generating flashcards:", error);
    throw error;
  }
}
// fetch the videos from the backend

export const fetchVideos = async (lesson_id,quiz_ress_id,isProfessor)  => {
  const token = localStorage.getItem("access_token") || null;
  try {
    const response = await axios.get(API_BASE_URL + `/api/youtube/${lesson_id}/${quiz_ress_id}`, {
      params: isProfessor ? { isFromProf: true } : {},
      headers: {
        'Content-Type': 'application/json',
        "Authorization": `Bearer ${token}`
      },
    });
    // Log the response for debugging
    console.log('Videos fetched:', response.data);
    return response.data;
  } catch (error) {
    console.error("Error fetching videos:", error);
    throw error;
  }
}
// get quiz by _id 
export const getQuizById = async (quiz_id) => {
  const token = localStorage.getItem("access_token") || null;
  try {
    const response = await axios.get(API_BASE_URL + `/api/quizzes/${quiz_id}`, {
      headers: {
        'Content-Type': 'application/json',
        "Authorization": `Bearer ${token}`
      },
    });
    // Log the response for debugging
    console.log('Quiz fetched:', response.data);
    return response.data;
  }
  catch (error) {
    console.error("Error fetching quiz:", error);
    throw error;
  }
}

// get all the flashcards generated by the user
export const getFlashcards = async (user_id) => {
  const token = localStorage.getItem("access_token") || null;
  try {
    const response = await axios.get(API_BASE_URL + `/api/flashcards/Fetch_All/${user_id}`, {
      headers: {
        'Content-Type': 'application/json',
        "Authorization": `Bearer ${token}`
      },
    });
    // Log the response for debugging
    console.log('Flashcards fetched:', response.data);
    return response.data;
  }
  catch (error) {
    console.error("Error fetching flashcards:", error);
    throw error;
  }
}
// get single flashcard by resualt id
export const getFlashcardById = async (resualt_id) => {
  const token = localStorage.getItem("access_token") || null;
  try {
    const response = await axios.get(API_BASE_URL + `/api/flashcards/get/${resualt_id}`, {
      headers: {
        'Content-Type': 'application/json',
        "Authorization": `Bearer ${token}`
      },
    });
    // Log the response for debugging
    console.log('Flashcard fetched:', response.data);
    return response.data;
  }
  catch (error) {
    console.error("Error fetching flashcard:", error);
    throw error;
  }
}
//get all the quiz results generated by the user
export const getQuizResults = async (user_id) => {
  const token = localStorage.getItem("access_token") || null;
  try {
    const response = await axios.get(API_BASE_URL + `/api/quiz_results/${user_id}`, {
      headers: {
        'Content-Type': 'application/json',
        "Authorization": `Bearer ${token}`
      },
    });
    // Log the response for debugging
    console.log('Quiz results fetched:', response.data);
    return response.data;
  }
  catch (error) {
    console.error("Error fetching quiz results:", error);
    throw error;
  }
}
//get  the quiz results generated by resualt id
export const getQuizResultById = async (result_id) => {
  const token = localStorage.getItem("access_token") || null;
  try {
    const response = await axios.get(API_BASE_URL + `/api/quiz_results/get/${result_id}`, {
      headers: {
        'Content-Type': 'application/json',
        "Authorization": `Bearer ${token}`
      },
    });
    // Log the response for debugging
    console.log('Quiz result fetched:', response.data);
    return response.data;
  }
  catch (error) {
    console.error("Error fetching quiz result:", error);
    throw error;
  }
}
// get group info by group_id 
export const getGroupInfo = async (group_id) => {
  const token = localStorage.getItem("access_token") || null;
  try {
    const response = await axios.get(API_BASE_URL + `/api/groups/get/${group_id}`, {
      headers: {
        'Content-Type': 'application/json',
        "Authorization": `Bearer ${token}`
      },
    });
    // Log the response for debugging
    console.log('Group info fetched:', response.data);
    return response.data;
  }
  catch (error) {
    console.error("Error fetching group info:", error);
    throw error;
  }
}
//  get quiz assignments by group_id
export const getQuizAssignments = async (group_id) => {
  const token = localStorage.getItem("access_token") || null;
  try {
    const response = await axios.get(API_BASE_URL + `/api/group-assignments/${group_id}`, {
      headers: {
        'Content-Type': 'application/json',
        "Authorization": `Bearer ${token}`
      },
    });
    // Log the response for debugging
    console.log('Quiz assignments fetched:', response.data);
    return response.data;
  }
  catch (error) {
    console.error("Error fetching quiz assignments:", error);
    throw error;
  }
}
export const saveQuizAttempt = async (attempt) => {
  const token = localStorage.getItem("access_token") || null;
  try {
    // Fetch quiz title before saving attempt
    let title = '';
    if (attempt.quizId) {
      try {
        const quizResponse = await axios.get(API_BASE_URL + `/api/quizzes/${attempt.quizId}`, {
          headers: {
            'Content-Type': 'application/json',
            "Authorization": `Bearer ${token}`
          },
        });
        if (quizResponse.data && quizResponse.data.title) {
          title = quizResponse.data.title;
        }
      } catch (error) {
        console.error("Error fetching quiz title:", error);
      }
    }
    // Add title to attempt
    const attemptWithTitle = { ...attempt, title };

    const response = await axios.post(API_BASE_URL + "/api/student-quiz-attempt", { attempt: attemptWithTitle }, {
      headers: {
        'Content-Type': 'application/json',
        "Authorization": `Bearer ${token}`
      },
    });
    // Log the response for debugging
    console.log('Quiz attempt saved:', response.data);
    return response.data;
  }
  catch (error) {
    console.error("Error saving quiz attempt:", error);
    throw error;
  }
}

//  fetch  student performance across all quizzes
export const fetchStudentPerformance = async () => {
  const token = localStorage.getItem("access_token") || null;
  try {
    const response = await axios.get(API_BASE_URL + `/api/student-performance`, {
      headers: {
        'Content-Type': 'application/json',
        "Authorization": `Bearer ${token}`
      },
    });
    // Log the response for debugging
    console.log('Student performance fetched:', response.data);
    return response.data;
  }
  catch (error) {
    console.error("Error fetching student performance:", error);
    throw error;
  }
}

// fetch notifications for the authenticated user
export const fetchNotifications = async () => {
  const token = localStorage.getItem("access_token") || null;
  try {
    const response = await axios.get(API_BASE_URL + '/api/notification', {
      headers: {
        'Content-Type': 'application/json',
        "Authorization": `Bearer ${token}`
      },
    });
    console.log('Notifications fetched:', response.data);
    return response.data;
  } catch (error) {
    console.error("Error fetching notifications:", error);
    throw error;
  }
}

// get quiz attempt by id
export const getQuizAttemptById = async (attempt_id) => {
  const token = localStorage.getItem("access_token") || null;
  try {
    const response = await axios.get(`/api/quiz-attempts/get/${attempt_id}`, {
      headers: {
        'Content-Type': 'application/json',
        "Authorization": `Bearer ${token}`
      },
    });
    console.log('Quiz attempt fetched:', response.data);
    return response.data;
  } catch (error) {
    console.error("Error fetching quiz attempt:", error);
    throw error;
  }
}
