import axios from "axios";
// token
const token = localStorage.getItem("access_token") || null;
// uploade file or image or text to the server and create a lesson in the database , 
// return the lesson objectID
export const uploadLesson = async (data, title, type, username) => {
  const formData = new FormData();
  // Add common fields
  formData.append('title', title);
  formData.append('username', username);
  // Add content based on type
  if (type === 'file') {
    formData.append('file', data, data.name);
  } 
  else if (type === 'text') {
    formData.append('text', data);
  }

  // Log form data for debugging
  for (let [key, value] of formData.entries()) {
    console.log('FormData:', key, value);
  }

  try {
    const response = await axios.post(
    '/api/upload', 
      formData, 
      {
        headers: {
          'Content-Type': 'multipart/form-data',
          "Authorization": `Bearer ${token}`
        },
      }
    );
    // Log the response for debugging
    console.log('Upload response:', response.data);
    return response.data;
  } catch (error) {
    console.error("Error uploading file:", error);
    if (error.response) {
      // Server responded with error status
      throw new Error(error.response.data.message || 'Upload failed');
    } else if (error.request) {
      // No response received
      throw new Error('Network error - no response from server');
    } else {
      // Other errors
      throw new Error('Upload failed: ' + error.message);
    }
  }
}
// generate Quiz 
export const generateQuiz = async (quizsetup) => {
  try {
    const response = await axios.post(
      "/api/create_quiz",
      quizsetup,
      {
        headers: {
          'Content-Type': 'application/json',
          "Authorization": `Bearer ${token}`
        },
      }
    );
    // Log the response for debugging
    console.log('Quiz generation response:', response.data);
    return response.data;
  } catch (error) {
    console.error("Error generating quiz:", error);
    throw error;
  }
}
// save the quiz result to the database 
export const saveQuizResult = async (result) => {
  try {
    const response = await axios.post("/api/quiz_results/insert", {result}, {
        headers: {
          'Content-Type': 'application/json',
          "Authorization": `Bearer ${token}`
        },
      });
    // Log the response for debugging
    console.log('Quiz result saved:', response.data);
    return response.data;
  }
  catch (error) {
    console.error("Error saving quiz result:", error);
    throw error;
  }
}
// generate flashcards 
export const generateFlashcards = async (lesson_id,quiz_ress_id) => {
  try {
    const response = await axios.get(`/api/flashcards/${lesson_id}/${quiz_ress_id}`, {
      headers: {
        'Content-Type': 'application/json',
        "Authorization": `Bearer ${token}`
      },
    });
    // Log the response for debugging
    console.log('Flashcards generateed:', response.data);
    return response.data;
  }
  catch (error) {
    console.error("Error generating flashcards:", error);
    throw error;
  }
}
// fetch the videos from the backend

export const fetchVideos = async (lesson_id,quiz_ress_id)  => {
  try {
    const response = await axios.get(`/api/youtube/${lesson_id}/${quiz_ress_id}`, {
      headers: {
        'Content-Type': 'application/json',
        "Authorization": `Bearer ${token}`
      },
    });
    // Log the response for debugging
    console.log('Videos fetched:', response.data);
    return response.data;

  }
  catch (error) {
    console.error("Error fetching videos:", error);
    throw error;
  }
}
// get quiz by _id 
export const getQuizById = async (quiz_id) => {
  try {
    const response = await axios.get(`/api/quizzes/${quiz_id}`, {
      headers: {
        'Content-Type': 'application/json',
        "Authorization": `Bearer ${token}`
      },
    });
    // Log the response for debugging
    console.log('Quiz fetched:', response.data);
    return response.data;
  }
  catch (error) {
    console.error("Error fetching quiz:", error);
    throw error;
  }
}

// get all the flashcards generated by the user
export const getFlashcards = async (user_id) => {
  try {
    const response = await axios.get(`/api/flashcards/Fetch_All/${user_id}`, {
      headers: {
        'Content-Type': 'application/json',
        "Authorization": `Bearer ${token}`
      },
    });
    // Log the response for debugging
    console.log('Flashcards fetched:', response.data);
    return response.data;
  }
  catch (error) {
    console.error("Error fetching flashcards:", error);
    throw error;
  }
}
// get single flashcard by resualt id
export const getFlashcardById = async (resualt_id) => {
  try {
    const response = await axios.get(`/api/flashcards/get/${resualt_id}`, {
      headers: {
        'Content-Type': 'application/json',
        "Authorization": `Bearer ${token}`
      },
    });
    // Log the response for debugging
    console.log('Flashcard fetched:', response.data);
    return response.data;
  }
  catch (error) {
    console.error("Error fetching flashcard:", error);
    throw error;
  }
}
//get all the quiz results generated by the user
export const getQuizResults = async (user_id) => {
  try {
    const response = await axios.get(`/api/quiz_results/${user_id}`, {
      headers: {
        'Content-Type': 'application/json',
        "Authorization": `Bearer ${token}`
      },
    });
    // Log the response for debugging
    console.log('Quiz results fetched:', response.data);
    return response.data;
  }
  catch (error) {
    console.error("Error fetching quiz results:", error);
    throw error;
  }
}
//get  the quiz results generated by resualt id
export const getQuizResultById = async (result_id) => {
  try {
    const response = await axios.get(`/api/quiz_results/get/${result_id}`, {
      headers: {
        'Content-Type': 'application/json',
        "Authorization": `Bearer ${token}`
      },
    });
    // Log the response for debugging
    console.log('Quiz result fetched:', response.data);
    return response.data;
  }
  catch (error) {
    console.error("Error fetching quiz result:", error);
    throw error;
  }
}
// get group info by group_id 
export const getGroupInfo = async (group_id) => {
  try {
    const response = await axios.get(`/api/groups/get/${group_id}`, {
      headers: {
        'Content-Type': 'application/json',
        "Authorization": `Bearer ${token}`
      },
    });
    // Log the response for debugging
    console.log('Group info fetched:', response.data);
    return response.data;
  }
  catch (error) {
    console.error("Error fetching group info:", error);
    throw error;
  }
}
//  get quiz assignments by group_id
export const getQuizAssignments = async (group_id) => {
  try {
    const response = await axios.get(`/api/group-assignments/${group_id}`, {
      headers: {
        'Content-Type': 'application/json',
        "Authorization": `Bearer ${token}`
      },
    });
    // Log the response for debugging
    console.log('Quiz assignments fetched:', response.data);
    return response.data;
  }
  catch (error) {
    console.error("Error fetching quiz assignments:", error);
    throw error;
  }
}
//  save quiz attempt for a student
export const saveQuizAttempt = async (attempt) => {
  try {
    const response = await axios.post("/api/student-quiz-attempt", { attempt }, {
      headers: {
        'Content-Type': 'application/json',
        "Authorization": `Bearer ${token}`
      },
    });
    // Log the response for debugging
    console.log('Quiz attempt saved:', response.data);
    return response.data;
  }
  catch (error) {
    console.error("Error saving quiz attempt:", error);
    throw error;
  }
}

//  fetch  student performance across all quizzes
export const fetchStudentPerformance = async () => {
  try {
    const response = await axios.get(`/api/student-performance`, {
      headers: {
        'Content-Type': 'application/json',
        "Authorization": `Bearer ${token}`
      },
    });
    // Log the response for debugging
    console.log('Student performance fetched:', response.data);
    return response.data;
  }
  catch (error) {
    console.error("Error fetching student performance:", error);
    throw error;
  }
}
